%==========================================================================
%Unit tests for testing features of the viewer. To run the below run the 
%runTest function.
%
%Authors: Thomas Maullin, Camille Maumet.
%==========================================================================

classdef ibma_test_pubBias < matlab.unittest.TestCase
       
    methods
        %Function for deleting any previous nii files.
        function deleteNII(testCase, data_path, type)
            close all;
            %If it's an egger weighted test, deleted any weighted egger
            %files.
            if strcmp(type, 'EWRegression')
                index = fullfile(data_path, 'ewpiRegressionMap.nii');
                if exist(index, 'file')
                    delete(index);
                end
                index = fullfile(data_path, 'ewiRegressionMap.nii');
                if exist(index, 'file')
                    delete(index);
                end
            %If it's an egger unweighted test, deleted any unweighted egger
            %files.
            elseif strcmp(type, 'EURegression')
                index = fullfile(data_path, 'eupiRegressionMap.nii');
                if exist(index, 'file')
                    delete(index);
                end
                index = fullfile(data_path, 'euiRegressionMap.nii');
                if exist(index, 'file')
                    delete(index);
                end
            %If it's a Trim And Fill test, deleted any Trim And Fill
            %files.
            elseif strcmp(type, 'TrimAndFill')
                index = fullfile(data_path, 'RTrimAndFillMap.nii');
                if exist(index, 'file')
                    delete(index);
                end
                index = fullfile(data_path, 'LTrimAndFillMap.nii');
                if exist(index, 'file')
                    delete(index);
                end
                index = fullfile(data_path, 'QTrimAndFillMap.nii');
                if exist(index, 'file')
                    delete(index);
                end
            %If it's a Beggs Correlation test, deleted any Beggs
            %Correlation files.
            elseif strcmp(type, 'BeggsCorrelation')
                index = fullfile(data_path, 'zBeggsCorrelationMap.nii');
                if exist(index, 'file')
                    delete(index);
                end
                index = fullfile(data_path, 'tBeggsCorrelationMap.nii');
                if exist(index, 'file')
                    delete(index);
                end
                index = fullfile(data_path, 'pBeggsCorrelationMap.nii');
                if exist(index, 'file')
                    delete(index);
                end
            %If it's a Macaskill's regression test, deleted any Macaskill's
            %regression files.
            else
                index = fullfile(data_path, 'mpsRegressionMap.nii');
                if exist(index, 'file')
                    delete(index);
                end
                index = fullfile(data_path, 'msRegressionMap.nii');
                if exist(index, 'file')
                    delete(index);
                end
            end
        end
    end
        
    methods(Test)
        
        %Checking Trim And Fill Q runs.
        function trimAndFill_Q(testCase)
            data_output_path = fullfile(fileparts(mfilename('fullpath')), '..');
            data_input_path = fullfile(fileparts(mfilename('fullpath')), '..', 'ibma_data');
            matlabbatch{1}.spm.tools.ibma.diagbias.statType.statType_trimAndFill.statType_trimAndFill_Q.dataEntry.dataEntry_files.dir = {data_output_path};
            matlabbatch{1}.spm.tools.ibma.diagbias.statType.statType_trimAndFill.statType_trimAndFill_Q.dataEntry.dataEntry_files.ConE = {...
                      [fullfile(data_input_path, 'pain_01','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_02','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_03','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_04','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_05','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_06','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_07','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_08','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_09','Contrast.nii'),',1']};
            matlabbatch{1}.spm.tools.ibma.diagbias.statType.statType_trimAndFill.statType_trimAndFill_Q.dataEntry.dataEntry_files.ConSE = {...
                      [fullfile(data_input_path, 'pain_01','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_02','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_03','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_04','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_05','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_06','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_07','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_08','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_09','ContrastStandardError.nii'),',1']};
            matlabbatch{1}.spm.tools.ibma.diagbias.masking.tm.tm_none = 1;
            matlabbatch{1}.spm.tools.ibma.diagbias.masking.im = 1;
            matlabbatch{1}.spm.tools.ibma.diagbias.masking.em = {''};
            spm_jobman('run', matlabbatch);
            deleteNII(testCase, data_output_path, 'TrimAndFill');
        end
        
        function trimAndFill_L(testCase)
            data_output_path = fullfile(fileparts(mfilename('fullpath')), '..');
            data_input_path = fullfile(fileparts(mfilename('fullpath')), '..', 'ibma_data');
            matlabbatch{1}.spm.tools.ibma.diagbias.statType.statType_trimAndFill.statType_trimAndFill_L.dataEntry.dataEntry_files.dir = {data_output_path};
            matlabbatch{1}.spm.tools.ibma.diagbias.statType.statType_trimAndFill.statType_trimAndFill_L.dataEntry.dataEntry_files.ConE = {...
                      [fullfile(data_input_path, 'pain_01','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_02','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_03','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_04','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_05','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_06','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_07','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_08','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_09','Contrast.nii'),',1']};
            matlabbatch{1}.spm.tools.ibma.diagbias.statType.statType_trimAndFill.statType_trimAndFill_L.dataEntry.dataEntry_files.ConSE = {...
                      [fullfile(data_input_path, 'pain_01','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_02','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_03','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_04','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_05','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_06','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_07','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_08','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_09','ContrastStandardError.nii'),',1']};
            matlabbatch{1}.spm.tools.ibma.diagbias.masking.tm.tm_none = 1;
            matlabbatch{1}.spm.tools.ibma.diagbias.masking.im = 1;
            matlabbatch{1}.spm.tools.ibma.diagbias.masking.em = {''};
            spm_jobman('run', matlabbatch);
            deleteNII(testCase, data_output_path, 'TrimAndFill');
        end
        
        function trimAndFill_R(testCase)
            data_output_path = fullfile(fileparts(mfilename('fullpath')), '..');
            data_input_path = fullfile(fileparts(mfilename('fullpath')), '..', 'ibma_data');
            matlabbatch{1}.spm.tools.ibma.diagbias.statType.statType_trimAndFill.statType_trimAndFill_R.dataEntry.dataEntry_files.dir = {data_output_path};
            matlabbatch{1}.spm.tools.ibma.diagbias.statType.statType_trimAndFill.statType_trimAndFill_R.dataEntry.dataEntry_files.ConE = {...
                      [fullfile(data_input_path, 'pain_01','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_02','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_03','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_04','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_05','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_06','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_07','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_08','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_09','Contrast.nii'),',1']};
            matlabbatch{1}.spm.tools.ibma.diagbias.statType.statType_trimAndFill.statType_trimAndFill_R.dataEntry.dataEntry_files.ConSE = {...
                      [fullfile(data_input_path, 'pain_01','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_02','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_03','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_04','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_05','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_06','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_07','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_08','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_09','ContrastStandardError.nii'),',1']};
            matlabbatch{1}.spm.tools.ibma.diagbias.masking.tm.tm_none = 1;
            matlabbatch{1}.spm.tools.ibma.diagbias.masking.im = 1;
            matlabbatch{1}.spm.tools.ibma.diagbias.masking.em = {''};
            spm_jobman('run', matlabbatch);
            deleteNII(testCase, data_output_path, 'TrimAndFill');
        end
        
        function BeggsCorrelation_z(testCase)
            data_output_path = fullfile(fileparts(mfilename('fullpath')), '..');
            data_input_path = fullfile(fileparts(mfilename('fullpath')), '..', 'ibma_data');
            matlabbatch{1}.spm.tools.ibma.diagbias.statType.statType_BeggsCorrelation.statType_BeggsCorrelation_z.dataEntry.dataEntry_files.dir = {data_output_path};
            matlabbatch{1}.spm.tools.ibma.diagbias.statType.statType_BeggsCorrelation.statType_BeggsCorrelation_z.dataEntry.dataEntry_files.ConE = {...
                      [fullfile(data_input_path, 'pain_01','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_02','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_03','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_04','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_05','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_06','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_07','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_08','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_09','Contrast.nii'),',1']};
            matlabbatch{1}.spm.tools.ibma.diagbias.statType.statType_BeggsCorrelation.statType_BeggsCorrelation_z.dataEntry.dataEntry_files.ConSE = {...
                      [fullfile(data_input_path, 'pain_01','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_02','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_03','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_04','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_05','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_06','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_07','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_08','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_09','ContrastStandardError.nii'),',1']};
            matlabbatch{1}.spm.tools.ibma.diagbias.masking.tm.tm_none = 1;
            matlabbatch{1}.spm.tools.ibma.diagbias.masking.im = 1;
            matlabbatch{1}.spm.tools.ibma.diagbias.masking.em = {''};
            spm_jobman('run', matlabbatch);
            deleteNII(testCase, data_output_path, 'BeggsCorrelation');
        end
        
        function BeggsCorrelation_p(testCase)
            data_output_path = fullfile(fileparts(mfilename('fullpath')), '..');
            data_input_path = fullfile(fileparts(mfilename('fullpath')), '..', 'ibma_data');
            matlabbatch{1}.spm.tools.ibma.diagbias.statType.statType_BeggsCorrelation.statType_BeggsCorrelation_p.dataEntry.dataEntry_files.dir = {data_output_path};
            matlabbatch{1}.spm.tools.ibma.diagbias.statType.statType_BeggsCorrelation.statType_BeggsCorrelation_p.dataEntry.dataEntry_files.ConE = {...
                      [fullfile(data_input_path, 'pain_01','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_02','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_03','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_04','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_05','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_06','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_07','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_08','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_09','Contrast.nii'),',1']};
            matlabbatch{1}.spm.tools.ibma.diagbias.statType.statType_BeggsCorrelation.statType_BeggsCorrelation_p.dataEntry.dataEntry_files.ConSE = {...
                      [fullfile(data_input_path, 'pain_01','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_02','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_03','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_04','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_05','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_06','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_07','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_08','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_09','ContrastStandardError.nii'),',1']};
            matlabbatch{1}.spm.tools.ibma.diagbias.masking.tm.tm_none = 1;
            matlabbatch{1}.spm.tools.ibma.diagbias.masking.im = 1;
            matlabbatch{1}.spm.tools.ibma.diagbias.masking.em = {''};
            spm_jobman('run', matlabbatch);
            deleteNII(testCase, data_output_path, 'BeggsCorrelation');
        end
        
        function BeggsCorrelation_t(testCase)
            data_output_path = fullfile(fileparts(mfilename('fullpath')), '..');
            data_input_path = fullfile(fileparts(mfilename('fullpath')), '..', 'ibma_data');
            matlabbatch{1}.spm.tools.ibma.diagbias.statType.statType_BeggsCorrelation.statType_BeggsCorrelation_t.dataEntry.dataEntry_files.dir = {data_output_path};
            matlabbatch{1}.spm.tools.ibma.diagbias.statType.statType_BeggsCorrelation.statType_BeggsCorrelation_t.dataEntry.dataEntry_files.ConE = {...
                      [fullfile(data_input_path, 'pain_01','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_02','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_03','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_04','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_05','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_06','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_07','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_08','Contrast.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_09','Contrast.nii'),',1']};
            matlabbatch{1}.spm.tools.ibma.diagbias.statType.statType_BeggsCorrelation.statType_BeggsCorrelation_t.dataEntry.dataEntry_files.ConSE = {...
                      [fullfile(data_input_path, 'pain_01','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_02','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_03','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_04','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_05','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_06','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_07','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_08','ContrastStandardError.nii'),',1'];...
                      [fullfile(data_input_path, 'pain_09','ContrastStandardError.nii'),',1']};
            matlabbatch{1}.spm.tools.ibma.diagbias.masking.tm.tm_none = 1;
            matlabbatch{1}.spm.tools.ibma.diagbias.masking.im = 1;
            matlabbatch{1}.spm.tools.ibma.diagbias.masking.em = {''};
            spm_jobman('run', matlabbatch);
            deleteNII(testCase, data_output_path, 'BeggsCorrelation');
        end
        
    end
end